# ----
# Site

title: Mountain Fog
url: "https://www.philter.app"
baseurl:
locale: en_US
links_philter_aws: https://aws.amazon.com/marketplace/pp/B07YVB8FFT?ref=_ptnr_mf_launch

# jekyll-seo-tag - https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
logo: /siteicon.png
description: Mountain fog website
author:
  name: Mountain Fog Team
  email: support@mtnfog.com
  twitter: mtnfog
twitter:
  - username: mtnfog
  - card: Software to redact sensitive information.

timezone: America/New_York
encoding: utf-8
paginate: 10
paginate_path: "/blog/:num/"
permalink: "/blog/:title/"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: false
